# Generated by Django 3.2.9 on 2022-04-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gammas', '0002_rename_action_gamma_gamma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamma',
            name='gamma',
            field=models.CharField(choices=[('0.1', '0.1'), ('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5'), ('0.6', '0.6'), ('0.7', '0.7'), ('0.8', '0.8'), ('0.9', '0.9'), ('1.0', '1.0')], max_length=50),
        ),
    ]
