# Generated by Django 3.2.9 on 2022-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gammas', '0003_alter_gamma_gamma'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamma',
            name='a',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='gamma',
            name='b',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamma',
            name='gamma',
            field=models.CharField(max_length=10),
        ),
    ]
